@startuml
  interface CLI
  interface Web
  interface WebSocket

package "<%= package.name %>" #<%= package.color.replace('#','') %> {
  component express as REST
  component socket.io as socket
  folder bin #ffffff {
    component "<%= package.prefix.replace(/\//g,' ') %>" as binName
  }
  binName --> REST

  folder deploy #ffffff {
      file "<%= package.deploy.name %>" as <%= package.deploy.name %>_container
      REST --> <%= package.deploy.name %>container

  <% for(let bname in package.deploy.build) {
    let build = package.deploy.build[bname];
    let bcmd = build.cmd;
    if(!bcmd) { bcmd = bname }
  %>
    file "<%= bcmd %>" as <%= bname %>_container
    REST --> <%= bname %>_container
    socket ---> <%= bname %>_container
  <% } %>
  }
  folder images #ffffff {
    collections "<%= package.deploy.name %>" as <%= package.deploy.name %>image
    artifact "ailtire:swarm" as ailtireswarm
    <%= package.deploy.name %>image <|-- ailtireswarm
    <%= package.deploy.name %>_container --> <%= package.deploy.name %>image

  <% for(let bname in package.deploy.build) {
      let build = package.deploy.build[bname];
      let buildtag = build.tag.replace(/:/g, '_');
    %>
      artifact "<%= build.tag %>" as <%= buildtag %>
      <%= bname %>_container --> <%= buildtag %>
    <% } %>
  }
}
CLI "<%= package.prefix.replace(/\//g, ' ') %>" -- binName
Web "<%= package.prefix %>" - REST
WebSocket "<%= package.prefix.replace(/\//g, '.' %>" -- socket

@enduml
