@startuml

<%
let pkgs = {};
let spkgs = package.subpackages;

for(let i in package.depends) {
    let dpackage = package.depends[i];
    if(spkgs) {
        if(!spkgs.hasOwnProperty(dpackage.shortname)) {
            pkgs[dpackage.shortname] = {name: dpackage.name, color:dpackage.color, classes:{}};
        }
    } else {
        pkgs[dpackage.shortname] = {name: dpackage.name, color:dpackage.color, classes:{}};
    }
}
for(let cname in package.classes) {
    let cls = package.classes[cname].definition;
    for(let aname in cls.associations) {
        let assoc = cls.associations[aname];
        let atype = assoc.type;
        let aclass = global.classes[atype];
        if(aclass) {
            let package = aclass.definition.package;
            if(spkgs) {
                if(!spkgs.hasOwnProperty(package.shortname)) {
                    if(!pkgs.hasOwnProperty(package.shortname)) {
                        pkgs[package.shortname] = {name: package.name, color: package.color, classes:{}};
                    }
                    pkgs[package.shortname].classes[atype] = 1;
                }
            } else {
                if(!pkgs.hasOwnProperty(package.shortname)) {
                    pkgs[package.shortname] = {name: package.name, color: package.color, classes:{}};
                }
                pkgs[package.shortname].classes[atype] = 1;
            }
        }
    }
}
for(let pname in pkgs) {
    let package = pkgs[pname];
%>
package "<%= package.name %>" #<%= package.color.replace('#','') %> {

}
<% } %>

package "<%= package.name %>" #<%= package.color.replace('#','') %> {

    interface "<%= package.name %>" as i {
    <% for (let hname in package.handlers) {
    -%>
        ^<%= hname %>
    <% } %>
    <% for (let iname in package.interface) {
        let inter = package.interface[iname];
    -%>
        <%= iname %>()
    <% } %>
    }
}

circle REST
circle Web
circle CLI
circle WebSocket

i -down- Web
i -down- CLI
i -down- REST
WebSocket -left- i: events >

package "<%= package.name %>" #<%= package.color.replace('#','') %> {

<% for(let spname in package.subpackages) {
    let package = package.subpackages[spname];
%>
rectangle "<%= package.name %>" #white {
}
<% } -%>
<% for(let spname in package.subpackages) {
    let spackage = package.subpackages[spname];
    for(let i in spackage.depends) {
    let dpackage = spackage.depends[i];
    %>
    "<%= spackage.name %>" --> "<%= dpackage.name %>"
    <%
    }
}
%>
}

<% for(let i in package.depends) {
    let dpackage = package.depends[i];
    %>
    "<%= dpackage.name %>" <-- "<%= package.name %>"
<% } %>

@enduml
