@startuml

class "<%- model.name %>" as Model {
<% for(let aname in model.attributes) {
    let attr = model.attributes[aname];
-%> <%= attr.type %> <%= aname %>
<% } %>
 <% for(let mname in model.methods) {
     let method = model.methods[mname];
 -%><%= mname %>()
 <% } %>
}

<% for(let aname in model.associations) {
    let assoc = model.associations[aname];
-%>
rectangle "<%= assoc.type %>" as <%= assoc.type %> #lightblue {
}
<% if(assoc.owner) { %>
Model *--> "<%= assoc.cardinality %>" <%= assoc.type %> : <%= aname %>
<% } else { %>
Model o--> "<%= assoc.cardinality %>" <%= assoc.type %> : <%= aname %>
<% } %>

<% } %>

<% for(let dname in model.dependant) {
    let depend = model.dependant[dname];
    let d = depend.model.name.replace(/\s/,'');
-%>
    rectangle "<%= depend.model.name %>" as <%= d %> #lightgreen {
    }
    <% if(depend.assoc.owner) { %>
        <%= d %>   *--> "<%= depend.assoc.cardinality %>" Model : "<%= depend.assoc.name %>"
    <% } else { %>
        <%= d %>   o--> "<%= depend.assoc.cardinality %>" Model : "<%= depend.assoc.name %>"
    <% } %>
<% } %>
@enduml
