@startuml

left to right direction
<%
let pkgMapping = {};
for(let p in global.packages) {
    let package = global.packages[p];
    pkgMapping[package.prefix] = package;
}
for(let i in actors) {
    let actor = actors[i];
    let anameNoSpace = actor.name.replace(/ /g, '') %>
Actor "<%= actor.name %>" as <%= anameNoSpace %>
<% } %>

<%
let j = 0;
for(let pname in actorPackages) {
    j++;
    let package = actorPackages[pname];
    let package = global.packages[pname];
    let pkgs = package.prefix.split(/\//);
    package = pkgMapping['/' + pkgs[1] + '/' + pkgs[2]];
    if(!package) {
        pkgMapping[pname] = global.packages[pname];
        package = pkgMapping[pname];
    }
%>
rectangle "<%= package.name %>" as <%= package.shortname %>  #<%= package.color.replace('#','') %> {
    <% for(let uname in package.usecases) {
        let usecase = package.usecases[uname];
    -%>
    usecase "<%= usecase.name %>" as <%= uname %>
    <%
    for(let aname in usecase.actors) {
        %>
        <%= aname.replace(/ /g, '') %> <%='-'.repeat(j % 2) %>--> <%= uname %>
        <%
    }
    %>
<% } %>
}
<% } %>

@enduml
