@startuml

skinparam packageStyle rect

package ailtire #lightgray {
    package "Use Case Model" #white {
        package "UseCase" #lightyellow {
        }
        package "Scenario" #lightyellow {
        }
        package "Step" #lightyellow {
        }
        package "Actor" #lightyellow {
        }
    }
    package "Deployment" #white {
        package "Interface" #ffccaa {
        }

        package "Micro-Service" as ms #ffccaa {
        }
        package "Micro-Segmented\nNetwork" as msn #ffccaa {
        }
        package "Service Stack" as ss #ffccaa {
        }
        ss "n" *--> "1" ms
        ss "n" *--> "1" msn
        Interface --> ms
    }

    package "Physical" #white {
        package "Compute" #lightgray { }
        package "Storage" #lightgray { }
        package "Network" #lightgray { }
        package "Location" #lightgray { }
        Location *--> Compute
        Location *--> Network
        Location *--> Storage
    }
    package "Process" #white {
        package "Workflow" #lightgreen { }
        package "Activity" #lightgreen { }
        package "Workspace" #lightgreen { }
        Workflow o-> Activity
        Activity --> Workspace : runs in
        Activity --|> Workflow
    }
    package Logical #white {
        package "Package" as package #lightblue {
        }
        package "Action" #lightblue {
        }
        package "Model" as Model #lightblue {
        }
    }
    package "Implementation" #white {
        package "Component" #lavender { }
        package "Environment" #lavender { }
        package "Image" #lavender { }
        Environment *-> "n" Component
        Environment *-> "n" Image
        Image --> "n" Component
    }
    package "Quality Assurance" #white {
        package "TestSuite" #pink { }
        package "Test" #pink { }
        TestSuite "1" *--> "n" Test
    }
    Environment ..> Location
    msn ..> Network
    ms ..> Compute
    Component ..> Storage
    Scenario -> Step
    Step --> Action
    Action --> Interface
    Image --> ms
    UseCase "1" *--> "n" Scenario
    UseCase "1" <- "n" Actor
    package "1" .> "n" ms
    package "1" .> "n" ss
    Scenario .> Action
    package -> UseCase
    package --> Model

    Actor ...> TestSuite
    UseCase ...> TestSuite
    Scenario ...> Test
    Test ...> Action

    Model -> Action
    package -> Action
    Workspace ..> ms
    Activity ..> Action
    Activity ..> Scenario
    Actor ..> Workflow

}

@enduml

