@startuml

<%
let pkgs = {};
for(let i in package.depends) {
    let dpackage = package.depends[i];
    pkgs[dpackage.shortname] = {name: dpackage.name, color:dpackage.color, classes:{}};
}
for(let cname in package.classes) {
    let cls = package.classes[cname];
    for(let aname in cls.associations) {
        let assoc = cls.associations[aname];
        let atype = assoc.type;
        let aclass = global.classes[atype];
        if(aclass) {
            let package = aclass.package;
            if(!pkgs.hasOwnProperty(package.shortname)) {
                pkgs[package.shortname] = {name: package.name, color: package.color, classes:{}};
            }
            pkgs[package.shortname].classes[atype] = 1;
        }
    }
}
for(let pname in pkgs) {
    let package = pkgs[pname];
%>
package "<%= package.name %>" #<%= package.color.replace('#', '') %> {
    <% for(let cname in package.classes) { %>
        class <%= cname %> {
        }
    <% } -%>
}
<% } %>

package "<%= package.name %>" #<%= package.color.replace('#', '') %> {

    interface "<%= package.name %>" as i {
    <% for (let iname in package.interface) {
        let inter = package.interface[iname];
    -%>
        <%= iname %>()
    <% } %>
    }
}

CLI ()-- i
REST ()-- i
Web ()-- i

package "<%= package.name %>" #<%= package.color.replace('#','') %> {
    <% for(let cname in package.classes) {
        let cls = package.classes[cname];
    -%>
    class "<%= cname %>" {
        <% for(let aname in cls.attributes) {
           let attr = cls.attributes[aname];
         -%>
         <%= attr.type %> <%= aname %>
        <% } -%>
        <% for(let mname in cls.methods) { -%>
             <%= mname %>()
        <% } -%>
    }
    <% for(let aname in cls.associations) {
        let assoc = cls.associations[aname];
        -%>
        <% if(assoc.owner) { -%>
    <%= cname %> *--> "<%= assoc.cardinality %>" <%= assoc.type %> : <%= aname %>
        <% } else { -%>
    <%= cname %> o--> "<%= assoc.cardinality %>" <%= assoc.type %> : <%= aname %>
        <% } -%>
    <% } %>
    <% if(cls.extends) { %>
        <%= cls.extends %> <|-- <%= cname %>
    <% } %>
<% } %>
}

<% for(let i in package.depends) {
    let dpackage = package.depends[i];
    %>
    "<%= package.name %>" --> "<%= dpackage.name %>"
<% } %>

@enduml
